name: Unit Integration

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ./ShiftrTests/ShiftrTests.csproj

      - name: Build
        run: dotnet build ./ShiftrTests/ShiftrTests.csproj --no-restore

      - name: Run integration tests
        run: dotnet test ./ShiftrTests/ShiftrTests.csproj --no-build --filter "Category=Integration" --logger "trx;LogFileName=integration-tests.trx" --results-directory ./TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults